// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAesBfjnv8Z_cgCgRbvMZ19JhiQcoR5GI4',
    appId: '1:54997654572:web:0c1291f6e3a13b3c738589',
    messagingSenderId: '54997654572',
    projectId: 'whatsappeg-9a5f4',
    authDomain: 'whatsappeg-9a5f4.firebaseapp.com',
    storageBucket: 'whatsappeg-9a5f4.appspot.com',
    measurementId: 'G-6FK9656QTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJRpBedhBai-P_IzP8f2-0kSu91IFLNGs',
    appId: '1:54997654572:android:44490bee457ad772738589',
    messagingSenderId: '54997654572',
    projectId: 'whatsappeg-9a5f4',
    storageBucket: 'whatsappeg-9a5f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXO37NBxD3O1WklSg2uxk6HDKWI-juSr0',
    appId: '1:54997654572:ios:ef8314d3a1f72674738589',
    messagingSenderId: '54997654572',
    projectId: 'whatsappeg-9a5f4',
    storageBucket: 'whatsappeg-9a5f4.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXO37NBxD3O1WklSg2uxk6HDKWI-juSr0',
    appId: '1:54997654572:ios:ef8314d3a1f72674738589',
    messagingSenderId: '54997654572',
    projectId: 'whatsappeg-9a5f4',
    storageBucket: 'whatsappeg-9a5f4.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAesBfjnv8Z_cgCgRbvMZ19JhiQcoR5GI4',
    appId: '1:54997654572:web:bd59778896ef44e2738589',
    messagingSenderId: '54997654572',
    projectId: 'whatsappeg-9a5f4',
    authDomain: 'whatsappeg-9a5f4.firebaseapp.com',
    storageBucket: 'whatsappeg-9a5f4.appspot.com',
    measurementId: 'G-0LTK4629GE',
  );
}
